DROP TABLE IF EXISTS species;
DROP TABLE IF EXISTS animal;

CREATE TABLE species(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL
);

CREATE TABLE animal(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	species_id INT NOT NULL
);
